[package]
name = "sort_benchmarking"
version = "0.1.0"
authors = ["Saurabh Raje <saurabh.mraje@gmail.com>"]
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
kvik = {git = "https://github.com/wagnerf42/kvik.git", rev="66de443"}
rayon = "1.3.0"
rand = "0.7.3"
